version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge
