name: Building Action

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installing Project dependency
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build
